#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 001
  第二次大戦中，イギリス・ケンブリッジのとあるパブ周辺で，物が奇妙にね
  じれるという出来事が相次いで起きた。戦時の混乱もあって真相はわからず
  じまいだったものの，戦後そのパブの常連だった2人の研究者から，DNAの二
  重らせん構造モデルが生まれている。



* 002
  中東のある砂漠には，正直者にだけ姿を現わす不思議なオアシスがあるとい
  う。それゆえとある部族では，罪の疑いがある者をその砂漠に捨て，生きて
  帰った者は無罪とするならわしがあった。多くの人々がそのしきたりで命を
  落としたが，生きて帰った者にのちの大統領フセインがいるそうだ。


  
* 003
  モテない男性が作りあげる架空の彼女，「嘘彼女」。近年の調査で，一部の
  嘘彼女に共通の特徴があることが判明した。その女性は自分の夢を叶えるた
  めフランスに留学し，そこで二人の関係が終わることがほとんどなのだが，
  その後実在の女性と結婚した男性の元には帰ってくるというのだ。



* 004
  世界に数多存在するネットラジオ。その中に，聞きなれない事件ばかりをと
  りあげる放送局があるという。大規模な災害が報じられることもあるが，当
  然そんな事実はない。興味本位で調べた者によると，該当するラジオ局は確
  かに実在するものの，開設は来年で，局が入る建物も現在建設中だという。



* 005
  「手でつかむ仕組み」を研究する学者がいた。ある日彼は軍にスカウトされ
  兵器の研究に携わった。「金欲しさに人殺しの研究をしている」と周囲に蔑
  まれ，彼は自殺した。後年その国は戦争を始めたが，敵国の兵士がたびたび
  不思議な報告をするようになった。「大きな手がミサイルを投げてくる」と。



* 注
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc/4.0/deed][Creative Commons Attribution-NonCommercial 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc/4.0/deed][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
