#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 011
  アジアのある地域では500年以上にわたって使われている赤い調味料がある。
  現在は唐辛子を使っているそうだが，かつては敵との戦いに勝利した証とし
  て，祝いの料理に用いられていたそうだ。だがアメリカ大陸原産の唐辛子が
  伝わる以前，どのようにして赤い色を生み出していたのだろうか。

* 012
  ある金融機関の主要なシステムで，半世紀以上前に開発されたプログラムが
  今でも使われているそうだ。たびたび置き換えの話が持ちあがるものの実現
  には至っていない。ある開発者によると，そのプログラムは言語仕様のバグ
  を利用して動いており，利率の算出が実際の値と異なるのだという。

* 013
  芸術家キャサリン・ベイの生涯には謎が多い。というのも，作品の実物を見
  た者の多くが心を病み，亡くなってしまうからだ。近年，老朽化した彼女の
  自宅を検査した際に死亡する者が続出した。その後のX線調査で，自宅の
  壁に未発表の作品が塗り込められているのがわかったという。

* 014
  南半球のある地域に，全身に赤や青の塗料を塗る奇妙な風習を持つ部族があっ
  た。彼らは武器を持たないにも関わらず，周辺の部族と争うことは決してな
  かったという。彼らはやがて滅びたものの，残されたミイラの血液から極め
  て感染力の高いウイルスが検出された。肌の塗料は警告色だったのだろうか。

* 015
  第二次大戦後の混乱期，日本からカリブ諸国への移民が行われた際に，日本
  へやってくる人々もいたそうだ。仕事のない彼らは，やがて故郷で親しんで
  いたサツマイモをもとに，焼き芋屋になったという。それが原因かは定かで
  はないが，「石焼き芋」のかけ声はカリブ音楽そっくりなのだそうだ。

<br>

[[https://github.com/jamcha-aa/Lore][目次]]

<br>

* 注
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
